j1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 2.0
    motor:
        id: 1
        init: 512
        min: 0
        max: 1024

j2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 2.0
    motor:
        id: 2
        init: 512
        min: 0
        max: 1024

joint_state_publisher:
   controller:
       package: spine_3
       module: joint_state_publisher
       type: JointStatePublisher

fullbody_controller:
   controller:
       #package: dynamixel_controllers
       package: spine_3
       module: joint_trajectory_action_controller
       type: JointTrajectoryActionController
   joint_trajectory_action_node:
       min_velocity: 0.0001
       constraints:
           goal_time: 0.0

